# Generated by Django 5.2.6 on 2025-12-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relay',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='priority'),
        ),
    ]
