# Generated by Django 5.2.1 on 2025-08-24 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_invoiceline_unit_name_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='person',
        ),
        migrations.AddField(
            model_name='employee',
            name='person_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.personaccount', verbose_name='person account'),
            preserve_default=False,
        ),
    ]
