# Generated by Django 5.2.1 on 2025-08-25 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_employee_person_employee_person_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organizationunit', verbose_name='organization_unit'),
        ),
    ]
