# Generated by Django 5.2.1 on 2025-05-17 20:46

import django.db.models.deletion
import tinymce.models
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=50, verbose_name='app_name')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='class_name')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('short_description', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='short_description')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=50000, null=True, verbose_name='description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('meta_data', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='meta_data')),
                ('priority', models.IntegerField(default=1000, verbose_name='ترتیب')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='images/ImageBase/Thumbnail/', verbose_name='تصویر کوچک')),
                ('header_origin', models.ImageField(blank=True, null=True, upload_to='images/ImageBase/Header/', verbose_name='تصویر سربرگ')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('muted', 'muted'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='color')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='core.page', verbose_name='parent')),
                ('related_pages', models.ManyToManyField(blank=True, to='core.page', verbose_name='related_pages')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.ImageHelper),
        ),
    ]
