# Generated by Django 5.2.1 on 2025-05-26 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('status', models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('در جریان', 'در جریان'), ('آماده تحویل', 'آماده تحویل'), ('تایید شده', 'تایید شده'), ('تحویل شده', 'تحویل شده'), ('کنسل شده', 'کنسل شده'), ('برگشت از تحویل', 'برگشت از تحویل'), ('تایید نهایی شده', 'تایید نهایی شده'), ('پاس شده', 'پاس شده'), ('مانده حساب از قبل', 'مانده حساب از قبل')], default='پیش نویس', max_length=50, verbose_name='وضعیت')),
                ('event_datetime', models.DateTimeField(verbose_name='event_datetime')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='start_datetime')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='end_datetime')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'رویداد ها',
            },
            bases=('core.page',),
        ),
    ]
