# Generated by Django 5.2.1 on 2025-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='header_origin',
            field=models.ImageField(blank=True, null=True, upload_to='core/images/page/header/', verbose_name='تصویر سربرگ'),
        ),
        migrations.AlterField(
            model_name='page',
            name='thumbnail_origin',
            field=models.ImageField(blank=True, null=True, upload_to='core/images/page/thumbnail/', verbose_name='تصویر کوچک'),
        ),
    ]
