# Generated by Django 5.2.4 on 2025-07-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_remove_location_page'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='locations',
            field=models.ManyToManyField(blank=True, to='attachments.location', verbose_name='locations'),
        ),
    ]
