# Generated by Django 5.2.1 on 2025-07-04 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='page',
        ),
        migrations.RemoveField(
            model_name='like',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
