# Generated by Django 5.2.1 on 2025-09-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date_updated'),
        ),
    ]
