# Generated by Django 5.2.1 on 2025-09-06 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_person_father_name'),
        ('core', '0004_page_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.person', verbose_name='ثبت شده توسط'),
        ),
    ]
