# Generated by Django 5.2.1 on 2025-09-06 05:58

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_page_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=50000, null=True, verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_data',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='متادیتا'),
        ),
        migrations.AlterField(
            model_name='page',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
