# Generated by Django 5.2.1 on 2025-08-10 13:50

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='room',
            field=models.CharField(default='gg', max_length=50, verbose_name='room'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='students',
            field=models.ManyToManyField(to='school.student', verbose_name='students'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='teachers',
            field=models.ManyToManyField(to='school.teacher', verbose_name='teachers'),
        ),
    ]
