# Generated by Django 5.2.1 on 2025-08-16 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='level',
            field=models.IntegerField(default=1, verbose_name='پایه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='students',
            field=models.ManyToManyField(blank=True, to='school.student', verbose_name='students'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='school.teacher', verbose_name='teachers'),
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('courses', models.ManyToManyField(blank=True, to='school.course', verbose_name='واحد های درسی')),
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Majors',
            },
        ),
        migrations.AddField(
            model_name='courseclass',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.major', verbose_name='major'),
            preserve_default=False,
        ),
    ]
