# Generated by Django 5.2.1 on 2025-08-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='educational_year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='educational_year'),
        ),
    ]
