# Generated by Django 5.2.1 on 2025-08-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('school', '0002_courseclass_level_alter_courseclass_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='books',
            field=models.ManyToManyField(blank=True, to='library.book', verbose_name='books'),
        ),
    ]
