# Generated by Django 5.2.1 on 2025-08-01 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_financialevent_creator'),
        ('school', '0002_remove_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='account',
        ),
        migrations.AddField(
            model_name='school',
            name='person_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.personaccount', verbose_name='person_account'),
        ),
    ]
