# Generated by Django 5.2.1 on 2025-09-03 17:19

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_courseclass_educational_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_no', models.IntegerField(verbose_name='session_no')),
                ('room', models.CharField(blank=True, max_length=50, null=True, verbose_name='room')),
                ('start_datetime', models.DateTimeField(verbose_name='start_datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='end_datetime')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.courseclass', verbose_name='course_class')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
            bases=(models.Model, utility.models.DateTimeHelper),
        ),
    ]
