# Generated by Django 5.2.1 on 2025-08-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_courseclass_room_student_courseclass_students_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'واحد های درسی'},
        ),
        migrations.AlterModelOptions(
            name='courseclass',
            options={'verbose_name': 'CourseClass', 'verbose_name_plural': 'واحد های درسی جاری'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'دانش آموز', 'verbose_name_plural': 'دانش آموزان'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'مربی', 'verbose_name_plural': 'مربی ها'},
        ),
    ]
