# Generated by Django 5.2.1 on 2025-09-03 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='وضعیت حضور')),
                ('score', models.IntegerField(verbose_name='score')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='description')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.session', verbose_name='session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'StudentInSession',
                'verbose_name_plural': 'StudentInSessions',
            },
        ),
    ]
