# Generated by Django 5.2.1 on 2025-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_studentinsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinsession',
            name='score',
            field=models.IntegerField(default=0, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='studentinsession',
            name='status',
            field=models.CharField(default='نامشخص', max_length=50, verbose_name='وضعیت حضور'),
        ),
    ]
