# Generated by Django 5.2.4 on 2025-10-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_studentinsession_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='personneli_code',
            field=models.CharField(default='2222', max_length=20, verbose_name='personneli_code'),
            preserve_default=False,
        ),
    ]
