# Generated by Django 5.2.1 on 2025-08-01 22:16

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('authentication', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organizationunit', verbose_name='organization_unit')),
                ('person_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.personaccount', verbose_name='person_account')),
            ],
            options={
                'verbose_name': 'WareHouse',
                'verbose_name_plural': 'WareHouses',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='MaterialTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.employee', verbose_name='employee')),
                ('ware_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'MaterialTerminal',
                'verbose_name_plural': 'MaterialTerminals',
            },
        ),
        migrations.CreateModel(
            name='MaterialPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('کیلوگرم', 'کیلوگرم'), ('متر', 'متر'), ('لیتر', 'لیتر'), ('سی سی ', 'سی سی '), ('شاخه', 'شاخه'), ('نود شبکه', 'نود شبکه'), ('شیشه', 'شیشه'), ('دستگاه', 'دستگاه'), ('گرم', 'گرم'), ('ورق', 'ورق'), ('تن', 'تن'), ('خط', 'خط'), ('پورس', 'پورس'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('روز', 'روز'), ('تخته', 'تخته'), ('لینک', 'لینک'), ('سرویس', 'سرویس'), ('مورد', 'مورد'), ('نفر', 'نفر'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست'), ('کارتن', 'کارتن'), ('ساعت', 'ساعت'), ('دقیقه', 'دقیقه'), ('جعبه', 'جعبه'), ('سبد', 'سبد'), ('راس', 'راس'), ('بطری', 'بطری')], default='عدد', max_length=100, verbose_name='unit_name')),
                ('direction', models.CharField(choices=[('ورود', 'ورود'), ('خروج', 'خروج')], max_length=50, verbose_name='direction')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.product', verbose_name='product')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_to', to='warehouse.warehouse', verbose_name='destination')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_from', to='warehouse.warehouse', verbose_name='source')),
            ],
            options={
                'verbose_name': 'MaterialPort',
                'verbose_name_plural': 'MaterialPorts',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='WareHouseMaterialSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('ورود', 'ورود'), ('خروج', 'خروج')], max_length=50, verbose_name='direction')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('کیلوگرم', 'کیلوگرم'), ('متر', 'متر'), ('لیتر', 'لیتر'), ('سی سی ', 'سی سی '), ('شاخه', 'شاخه'), ('نود شبکه', 'نود شبکه'), ('شیشه', 'شیشه'), ('دستگاه', 'دستگاه'), ('گرم', 'گرم'), ('ورق', 'ورق'), ('تن', 'تن'), ('خط', 'خط'), ('پورس', 'پورس'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('روز', 'روز'), ('تخته', 'تخته'), ('لینک', 'لینک'), ('سرویس', 'سرویس'), ('مورد', 'مورد'), ('نفر', 'نفر'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست'), ('کارتن', 'کارتن'), ('ساعت', 'ساعت'), ('دقیقه', 'دقیقه'), ('جعبه', 'جعبه'), ('سبد', 'سبد'), ('راس', 'راس'), ('بطری', 'بطری')], default='عدد', max_length=100, verbose_name='unit_name')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('shelf', models.CharField(max_length=50, verbose_name='shelf')),
                ('row', models.CharField(max_length=50, verbose_name='row')),
                ('col', models.CharField(max_length=50, verbose_name='col')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.product', verbose_name='product')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.person', verbose_name='person')),
                ('ware_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='ware_house')),
            ],
            options={
                'verbose_name': 'WareHouseMaterialSheet',
                'verbose_name_plural': 'WareHouseMaterialSheets',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
