# Generated by Django 5.2.1 on 2025-07-10 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_product_brand_product_model_productspecification'),
        ('organization', '0002_organizationunit_account'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='oragization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organizationunit', verbose_name='oragization_unit'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='account'),
        ),
    ]
