# Generated by Django 5.2.1 on 2025-08-25 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousematerialsheet',
            name='ware_house',
        ),
        migrations.AddField(
            model_name='warehousematerialsheet',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='warehouse'),
            preserve_default=False,
        ),
    ]
