# Generated by Django 5.2.1 on 2025-07-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehouse_oragization_unit_alter_warehouse_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='oragization_unit',
            new_name='organization_unit',
        ),
    ]
