# Generated by Django 5.2.1 on 2025-08-25 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_invoiceline_unit_name_and_more'),
        ('authentication', '0003_alter_person_economic_no'),
        ('warehouse', '0002_remove_warehousematerialsheet_ware_house_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WareHouseMaterialSheet',
            new_name='WareHouseSheet',
        ),
        migrations.AlterModelOptions(
            name='warehousesheet',
            options={'verbose_name': 'WareHouseSheet', 'verbose_name_plural': 'WareHouseSheets'},
        ),
    ]
