# Generated by Django 5.2.1 on 2025-07-31 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_profile_user_remove_person_profile_and_more'),
        ('warehouse', '0003_alter_materialport_unit_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialport',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='warehousematerialsheet',
            name='profile',
        ),
        migrations.AddField(
            model_name='materialport',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehousematerialsheet',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authentication.person', verbose_name='person'),
            preserve_default=False,
        ),
    ]
