# Generated by Django 5.2.1 on 2025-08-01 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_financialevent_creator'),
        ('warehouse', '0004_remove_materialport_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='account',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='person_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.personaccount', verbose_name='person_account'),
        ),
    ]
