# Generated by Django 5.2.6 on 2025-09-09 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_employee_organization_unit'),
        ('warehouse', '0005_alter_materialport_unit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouseSheetSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('تایید می شود', 'تایید می شود'), ('رد می شود', 'رد می شود')], max_length=50, verbose_name='status')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.employee', verbose_name='employee')),
                ('warehouse_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousesheet', verbose_name='warehouse_sheet')),
            ],
            options={
                'verbose_name': 'WareHouseSheetSignature',
                'verbose_name_plural': 'WareHouseSheetSignatures',
            },
        ),
    ]
