# Generated by Django 5.2.6 on 2025-09-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_warehousesheetsignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousesheetsignature',
            name='status',
            field=models.CharField(choices=[('درخواست می شود', 'درخواست می شود'), ('تایید می شود', 'تایید می شود'), ('رد می شود', 'رد می شود')], max_length=50, verbose_name='status'),
        ),
    ]
