# Generated by Django 5.2.6 on 2025-09-16 14:57

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_warehousesheetsignature_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouseSheetLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='serial_no')),
                ('lot_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='lot_no')),
                ('barcode_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='barcode_1')),
                ('barcode_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='barcode_2')),
                ('barcode_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='barcode_3')),
                ('label_origin', models.ImageField(blank=True, null=True, upload_to='warehouse/images/label', verbose_name='label_origin')),
                ('production_date', models.DateTimeField(blank=True, null=True, verbose_name='production_date')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='production_date')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('warehouse_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousesheet', verbose_name='warehouse_sheet')),
            ],
            options={
                'verbose_name': 'WareHouseSheetLabel',
                'verbose_name_plural': 'WareHouseSheetLabels',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
    ]
