# Generated by Django 5.2.6 on 2025-09-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_warehousesheetlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousesheetlabel',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expiration_date'),
        ),
    ]
