# Generated by Django 5.2.6 on 2025-09-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_financialdocumentline_status_and_more'),
        ('organization', '0003_alter_employee_organization_unit'),
        ('warehouse', '0009_alter_warehousesheetlabel_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='quantity')),
                ('unit_name', models.CharField(max_length=50, verbose_name='unit_name')),
                ('unit_price', models.IntegerField(verbose_name='unit_price')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('description', models.CharField(max_length=5000, verbose_name='description')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.invoice', verbose_name='invoice')),
                ('organization_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organizationunit', verbose_name='organization_unit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.product', verbose_name='product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'MaterialRequest',
                'verbose_name_plural': 'MaterialRequests',
            },
        ),
    ]
