# Generated by Django 5.2.6 on 2025-09-24 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_employee_organization_unit'),
        ('warehouse', '0010_materialrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousesheet',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organizationunit', verbose_name='organization_unit'),
        ),
        migrations.AlterField(
            model_name='warehousesheet',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='warehouse'),
        ),
    ]
