# Generated by Django 5.2.6 on 2025-09-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_warehousesheet_organization_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousesheetsignature',
            name='status',
            field=models.CharField(choices=[('درخواست می شود', 'درخواست می شود'), ('تایید می شود', 'تایید می شود'), ('رد می شود', 'رد می شود'), ('تحویل شد', 'تحویل شد')], max_length=50, verbose_name='status'),
        ),
    ]
