# Generated by Django 5.2.6 on 2025-09-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_employee_organization_unit'),
        ('warehouse', '0012_alter_warehousesheetsignature_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='employees',
            field=models.ManyToManyField(blank=True, to='organization.employee', verbose_name='employees'),
        ),
    ]
