# Generated by Django 5.2.6 on 2025-09-30 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_invoiceline_person'),
        ('warehouse', '0013_warehouse_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInWareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50, verbose_name='unit_name')),
                ('quantity', models.FloatField(verbose_name='quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.product', verbose_name='product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'ProductInWareHouse',
                'verbose_name_plural': 'ProductInWareHouses',
            },
        ),
    ]
