# Generated by Django 5.2.6 on 2025-10-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_productinwarehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousesheet',
            name='status',
            field=models.CharField(choices=[('درخواست می شود', 'درخواست می شود'), ('تایید می شود', 'تایید می شود'), ('رد می شود', 'رد می شود'), ('تحویل شد', 'تحویل شد')], default='www', max_length=50, verbose_name='status'),
            preserve_default=False,
        ),
    ]
