# Generated by Django 5.2.6 on 2025-10-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_warehousesheet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousesheet',
            name='status',
            field=models.CharField(choices=[('درخواست می شود', 'درخواست می شود'), ('تایید می شود', 'تایید می شود'), ('رد می شود', 'رد می شود'), ('تحویل شد', 'تحویل شد')], default='درخواست می شود', max_length=50, verbose_name='status'),
        ),
    ]
