# Generated by Django 5.2.6 on 2025-10-04 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_employee_organization_unit'),
        ('warehouse', '0016_alter_warehousesheet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousesheet',
            name='person',
        ),
        migrations.AddField(
            model_name='warehousesheet',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organization.employee', verbose_name='employee'),
            preserve_default=False,
        ),
    ]
