# Generated by Django 5.2.6 on 2025-10-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_remove_warehousesheet_person_warehousesheet_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousesheet',
            name='type',
            field=models.CharField(choices=[('فروش', 'فروش'), ('خرید', 'خرید'), ('انتقال', 'انتقال'), ('نامشخص', 'نامشخص')], default='نامشخص', max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='warehousesheet',
            name='status',
            field=models.CharField(choices=[('درخواست می شود', 'درخواست می شود'), ('تایید می شود', 'تایید می شود'), ('رد می شود', 'رد می شود'), ('بررسی می شود', 'بررسی می شود')], default='درخواست می شود', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='warehousesheetsignature',
            name='status',
            field=models.CharField(choices=[('درخواست می شود', 'درخواست می شود'), ('تایید می شود', 'تایید می شود'), ('رد می شود', 'رد می شود'), ('بررسی می شود', 'بررسی می شود')], max_length=50, verbose_name='status'),
        ),
    ]
