# Generated by Django 5.2.6 on 2025-10-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_warehousesheet_type_alter_warehousesheet_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousesheet',
            name='status',
            field=models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('درخواست می شود', 'درخواست می شود'), ('تایید می شود', 'تایید می شود'), ('رد می شود', 'رد می شود'), ('بررسی می شود', 'بررسی می شود')], default='درخواست می شود', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='warehousesheetsignature',
            name='status',
            field=models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('درخواست می شود', 'درخواست می شود'), ('تایید می شود', 'تایید می شود'), ('رد می شود', 'رد می شود'), ('بررسی می شود', 'بررسی می شود')], max_length=50, verbose_name='status'),
        ),
    ]
