# Generated by Django 5.2.1 on 2025-08-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_person_economic_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childs', models.ManyToManyField(blank=True, to='authentication.person', verbose_name='childs')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daddy_childs', to='authentication.person', verbose_name='father')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mommy_childs', to='authentication.person', verbose_name='mother')),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Familyes',
            },
        ),
    ]
