# Generated by Django 5.2.1 on 2025-07-02 22:56

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_alter_invoiceline_unit_name_and_more'),
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'MarketPerson',
                'verbose_name_plural': 'MarketPersons',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('marketperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.marketperson')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
            bases=('market.marketperson',),
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('marketperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.marketperson')),
            ],
            options={
                'verbose_name': 'Shipper',
                'verbose_name_plural': 'Shippers',
            },
            bases=('market.marketperson',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('marketperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.marketperson')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
            bases=('market.marketperson',),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('کیلوگرم', 'کیلوگرم'), ('متر', 'متر'), ('شاخه', 'شاخه'), ('شیشه', 'شیشه'), ('دستگاه', 'دستگاه'), ('گرم', 'گرم'), ('ورق', 'ورق'), ('تن', 'تن'), ('خط', 'خط'), ('پورس', 'پورس'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('روز', 'روز'), ('تخته', 'تخته'), ('لینک', 'لینک'), ('سرویس', 'سرویس'), ('مورد', 'مورد'), ('نفر', 'نفر'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست'), ('کارتن', 'کارتن'), ('ساعت', 'ساعت'), ('دقیقه', 'دقیقه'), ('جعبه', 'جعبه'), ('سبد', 'سبد'), ('راس', 'راس'), ('بطری', 'بطری')], max_length=50, verbose_name='unit_name')),
                ('unit_price', models.IntegerField(verbose_name='قیمت واحد')),
                ('discount_percentage', models.IntegerField(default=0, verbose_name='درصد تخفیف')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('available', models.IntegerField(verbose_name='available')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت ')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع ')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.product', verbose_name='product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='DeskCustomer',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.customer')),
            ],
            options={
                'verbose_name': 'DeskCustomer',
                'verbose_name_plural': 'DeskCustomers',
            },
            bases=('market.customer',),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(blank=True, default=1, verbose_name='ردیف')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shop', verbose_name='فروش')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'CartItem',
                'verbose_name_plural': 'CartItems',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('shops', models.ManyToManyField(blank=True, to='market.shop', verbose_name='shops')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
            bases=('core.page',),
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='code')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'Desk',
                'verbose_name_plural': 'Desks',
            },
        ),
    ]
