# Generated by Django 5.2.1 on 2025-05-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='unit_price',
            field=models.IntegerField(verbose_name='قیمت واحد'),
        ),
    ]
