# Generated by Django 5.2.1 on 2025-07-02 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskcustomer',
            name='desk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.desk', verbose_name='desk'),
            preserve_default=False,
        ),
    ]
