# Generated by Django 5.1.6 on 2025-07-12 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_person_title'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketperson',
            name='profile',
        ),
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.CharField(choices=[('میهمان', 'میهمان'), ('خریدار نهایی', 'خریدار نهایی'), ('فروشنده جزء', 'فروشنده جزء'), ('فروشنده کل', 'فروشنده کل')], default='خریدار نهایی', max_length=50, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='marketperson',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authentication.person', verbose_name='person'),
            preserve_default=False,
        ),
    ]
