# Generated by Django 5.1.6 on 2025-07-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_marketperson_profile_customer_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='level',
            field=models.CharField(choices=[('میهمان', 'میهمان'), ('خریدار نهایی', 'خریدار نهایی'), ('فروشنده جزء', 'فروشنده جزء'), ('فروشنده کل', 'فروشنده کل')], default='خریدار نهایی', max_length=50, verbose_name='level'),
        ),
    ]
