# Generated by Django 5.2.1 on 2025-07-28 11:52

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_shop_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='unit_name',
            field=models.CharField(choices=[('عدد', 'عدد'), ('کیلوگرم', 'کیلوگرم'), ('متر', 'متر'), ('لیتر', 'لیتر'), ('سی سی ', 'سی سی '), ('شاخه', 'شاخه'), ('نود شبکه', 'نود شبکه'), ('شیشه', 'شیشه'), ('دستگاه', 'دستگاه'), ('گرم', 'گرم'), ('ورق', 'ورق'), ('تن', 'تن'), ('خط', 'خط'), ('پورس', 'پورس'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('روز', 'روز'), ('تخته', 'تخته'), ('لینک', 'لینک'), ('سرویس', 'سرویس'), ('مورد', 'مورد'), ('نفر', 'نفر'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست'), ('کارتن', 'کارتن'), ('ساعت', 'ساعت'), ('دقیقه', 'دقیقه'), ('جعبه', 'جعبه'), ('سبد', 'سبد'), ('راس', 'راس'), ('بطری', 'بطری')], max_length=50, verbose_name='unit_name'),
        ),
        migrations.CreateModel(
            name='ShopPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('level', models.CharField(choices=[('میهمان', 'میهمان'), ('خریدار نهایی', 'خریدار نهایی'), ('فروشنده جزء', 'فروشنده جزء'), ('فروشنده کل', 'فروشنده کل')], default='خریدار نهایی', max_length=50, verbose_name='level')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع ')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان ')),
                ('quantity', models.IntegerField(verbose_name='تعداد کل')),
                ('available', models.IntegerField(verbose_name='موجود')),
                ('shops', models.ManyToManyField(to='market.shop', verbose_name='shops')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'ShopPackage',
                'verbose_name_plural': 'ShopPackages',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
