# Generated by Django 5.2.1 on 2025-07-02 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('market', '0002_alter_shop_unit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('shops', models.ManyToManyField(blank=True, to='market.shop', verbose_name='shops')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
            bases=('core.page',),
        ),
    ]
