# Generated by Django 5.2.1 on 2025-07-30 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_invoiceline_unit_name_and_more'),
        ('market', '0003_alter_shop_unit_name_shoppackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketperson',
            name='account',
        ),
        migrations.RemoveField(
            model_name='marketperson',
            name='person',
        ),
        migrations.AddField(
            model_name='marketperson',
            name='person_account',
            field=models.ForeignKey(default=623, on_delete=django.db.models.deletion.CASCADE, to='accounting.personaccount', verbose_name='person_account'),
            preserve_default=False,
        ),
    ]
