# Generated by Django 5.1.6 on 2025-07-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_supplier_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='level',
            field=models.CharField(choices=[('میهمان', 'میهمان'), ('خریدار نهایی', 'خریدار نهایی'), ('فروشنده جزء', 'فروشنده جزء'), ('فروشنده کل', 'فروشنده کل')], default='خریدار نهایی', max_length=50, verbose_name='level'),
        ),
    ]
