# Generated by Django 5.2.1 on 2025-07-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='date_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='date_start',
            new_name='start_date',
        ),
    ]
