# Generated by Django 5.2.6 on 2026-04-27 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_shop_unit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_cart', models.IntegerField(default=0, verbose_name='in_cart')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'MenuItem',
                'verbose_name_plural': 'MenuItems',
            },
        ),
    ]
