# Generated by Django 5.2.1 on 2025-07-31 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_profile_user_remove_person_profile_and_more'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='profile',
        ),
        migrations.AddField(
            model_name='log',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='authentication.person', verbose_name='person'),
        ),
    ]
