# Generated by Django 5.2.6 on 2026-04-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start_date'),
        ),
        migrations.AddField(
            model_name='blog',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='for home'),
        ),
        migrations.AddField(
            model_name='blog',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start_date'),
        ),
    ]
