# Generated by Django 5.2.4 on 2025-07-13 23:24

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0002_page_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('invoiceline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoiceline')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
            bases=('accounting.invoiceline',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('type', models.CharField(choices=[('تایپ A', 'تایپ A'), ('تایپ B', 'تایپ B')], default='تایپ A', max_length=50, verbose_name='تایپ')),
                ('percentage_completed', models.IntegerField(default=0, verbose_name='درصد پیشرفت')),
                ('weight', models.IntegerField(default=0, verbose_name='وزن پروژه')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
            bases=('core.event', utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='RemoteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('active_directory', models.CharField(blank=True, max_length=100, null=True, verbose_name='active_directory')),
                ('work_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='work_group')),
                ('os', models.CharField(blank=True, max_length=50, null=True, verbose_name='Operating System (os)')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='url')),
                ('local_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='local_ip')),
                ('remote_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='remote_ip')),
                ('any_desk_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='any_desk_address')),
                ('any_desk_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='any_desk_password')),
                ('dorsan_desk_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='dorsan_desk_address')),
                ('dorsan_desk_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='dorsan_desk_password')),
                ('model_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='model name')),
                ('id_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='id_name')),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='mac_address')),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='serial_no')),
                ('part_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='part_no')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='username')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='password')),
                ('identity', models.CharField(blank=True, max_length=50, null=True, verbose_name='identity')),
                ('wireless_mode', models.CharField(blank=True, max_length=50, null=True, verbose_name='wireless_mode')),
                ('wireless_band', models.CharField(blank=True, max_length=50, null=True, verbose_name='wireless_band')),
                ('ssid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ssid')),
                ('preshared_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='preshared_key')),
                ('frequency', models.CharField(blank=True, max_length=50, null=True, verbose_name='frequency')),
                ('protocol', models.CharField(blank=True, max_length=50, null=True, verbose_name='protocol')),
                ('channel_width', models.CharField(blank=True, max_length=50, null=True, verbose_name='channel_width')),
                ('adsl_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='adsl_username')),
                ('adsl_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='adsl_password')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='telephone')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='contact')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'RemoteClient',
                'verbose_name_plural': 'RemoteClients',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.request')),
            ],
            options={
                'verbose_name': 'MaterialRequest',
                'verbose_name_plural': 'MaterialRequests',
            },
            bases=('projectmanager.request',),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.request')),
            ],
            options={
                'verbose_name': 'ServiceRequest',
                'verbose_name_plural': 'ServiceRequests',
            },
            bases=('projectmanager.request',),
        ),
    ]
