# Generated by Django 5.2.1 on 2025-07-10 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_product_brand_product_model_productspecification'),
        ('organization', '0001_initial'),
        ('projectmanager', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='ware_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='ware_house'),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contracted', to='organization.organizationunit', verbose_name='contractor'),
        ),
        migrations.AddField(
            model_name='project',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_employed', to='organization.organizationunit', verbose_name='employer'),
        ),
        migrations.AddField(
            model_name='project',
            name='invoices',
            field=models.ManyToManyField(to='accounting.invoice', verbose_name='invoices'),
        ),
        migrations.AddField(
            model_name='remoteclient',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.brand', verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='project',
            name='remote_clients',
            field=models.ManyToManyField(to='projectmanager.remoteclient', verbose_name='remote_clients'),
        ),
    ]
