# Generated by Django 5.2.4 on 2025-07-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='invoices',
            field=models.ManyToManyField(blank=True, to='accounting.invoice', verbose_name='invoices'),
        ),
        migrations.AlterField(
            model_name='project',
            name='remote_clients',
            field=models.ManyToManyField(blank=True, to='projectmanager.remoteclient', verbose_name='remote_clients'),
        ),
    ]
