# Generated by Django 5.2.1 on 2025-07-14 13:06

import django.core.files.storage
import django.db.models.deletion
import tinymce.models
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='description')),
                ('datetime_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('type', models.CharField(choices=[('تایپ A', 'تایپ A'), ('تایپ B', 'تایپ B'), ('تایپ C', 'تایپ C')], max_length=50, verbose_name='تایپ')),
                ('status', models.CharField(choices=[('شروع شده', 'شروع شده'), ('در جریان', 'در جریان'), ('پایان یافته', 'پایان یافته')], default='شروع شده', max_length=50, verbose_name='وضعیت')),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='d:\\private_html\\phoenix11\\upload'), upload_to='projectmanager/ticket-files', verbose_name='فایل ضمیمه')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.ticket', verbose_name='parent')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.profile', verbose_name='پروفایل')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
            bases=(models.Model, utility.models.DateTimeHelper, utility.models.LinkHelper),
        ),
    ]
