# Generated by Django 5.2.1 on 2025-07-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_category'),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('invoiceline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoiceline')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
            bases=('accounting.invoiceline',),
        ),
        migrations.AddField(
            model_name='project',
            name='invoices',
            field=models.ManyToManyField(to='accounting.invoice', verbose_name='invoices'),
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.request')),
            ],
            options={
                'verbose_name': 'MaterialRequest',
                'verbose_name_plural': 'MaterialRequests',
            },
            bases=('projectmanager.request',),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.request')),
            ],
            options={
                'verbose_name': 'ServiceRequest',
                'verbose_name_plural': 'ServiceRequests',
            },
            bases=('projectmanager.request',),
        ),
    ]
