# Generated by Django 5.2.1 on 2025-08-10 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_bank_address_bank_branch_bank_tel_and_more'),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteclient',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.product', verbose_name='product'),
        ),
    ]
