# Generated by Django 5.1.6 on 2025-07-15 21:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='f:\\private_html\\phoenix11\\upload'), upload_to='projectmanager/ticket-files', verbose_name='فایل ضمیمه'),
        ),
    ]
