# Generated by Django 5.2.4 on 2025-07-10 05:01

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_brand'),
        ('projectmanager', '0002_request_project_invoices_materialrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('active_directory', models.CharField(blank=True, max_length=100, null=True, verbose_name='active_directory')),
                ('work_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='work_group')),
                ('os', models.CharField(blank=True, max_length=50, null=True, verbose_name='Operating System (os)')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='url')),
                ('local_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='local_ip')),
                ('remote_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='remote_ip')),
                ('any_desk_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='any_desk_address')),
                ('any_desk_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='any_desk_password')),
                ('dorsan_desk_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='dorsan_desk_address')),
                ('dorsan_desk_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='dorsan_desk_password')),
                ('model_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='model name')),
                ('id_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='id_name')),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='mac_address')),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='serial_no')),
                ('part_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='part_no')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='username')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='password')),
                ('identity', models.CharField(blank=True, max_length=50, null=True, verbose_name='identity')),
                ('wireless_mode', models.CharField(blank=True, max_length=50, null=True, verbose_name='wireless_mode')),
                ('wireless_band', models.CharField(blank=True, max_length=50, null=True, verbose_name='wireless_band')),
                ('ssid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ssid')),
                ('preshared_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='preshared_key')),
                ('frequency', models.CharField(blank=True, max_length=50, null=True, verbose_name='frequency')),
                ('protocol', models.CharField(blank=True, max_length=50, null=True, verbose_name='protocol')),
                ('channel_width', models.CharField(blank=True, max_length=50, null=True, verbose_name='channel_width')),
                ('adsl_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='adsl_username')),
                ('adsl_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='adsl_password')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='telephone')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='contact')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='description')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.brand', verbose_name='brand')),
            ],
            options={
                'verbose_name': 'RemoteClient',
                'verbose_name_plural': 'RemoteClients',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.AddField(
            model_name='project',
            name='remote_clients',
            field=models.ManyToManyField(to='projectmanager.remoteclient', verbose_name='remote_clients'),
        ),
    ]
