# Generated by Django 5.2.1 on 2025-08-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projectmanager', '0002_remoteclient_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='project_events', to='core.event', verbose_name='events'),
        ),
    ]
