# Generated by Django 5.2.1 on 2025-07-21 16:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_alter_ticket_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='d:\\private_html\\phoenix11\\upload'), upload_to='projectmanager/ticket-files', verbose_name='فایل ضمیمه'),
        ),
    ]
