# Generated by Django 5.2.1 on 2025-08-27 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_person_prefix'),
        ('projectmanager', '0003_project_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.person', verbose_name='شخص'),
        ),
    ]
