# Generated by Django 5.2.1 on 2025-07-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_alter_ticket_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='cost'),
        ),
    ]
