# Generated by Django 5.2.6 on 2025-09-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_alter_ticket_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteclient',
            name='pattern',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='pattern'),
        ),
    ]
