# Generated by Django 5.2.1 on 2025-07-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_project_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='ارزش پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='وزن پروژه'),
        ),
    ]
