# Generated by Django 5.2.1 on 2025-08-12 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0006_remove_account_logo_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('financialevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.financialevent')),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxs',
            },
            bases=('accounting.financialevent',),
        ),
    ]
