# Generated by Django 5.2.1 on 2025-07-04 20:46

import django.db.models.deletion
import utility.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='full_name')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='authentication/images/profile/', verbose_name='تصویر')),
                ('enabled', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
