# Generated by Django 5.2.1 on 2025-08-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='economic_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره اقنصادی'),
        ),
        migrations.AddField(
            model_name='person',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='person',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس'),
        ),
    ]
