# Generated by Django 5.2.1 on 2025-07-08 13:55

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('آقای', 'آقای'), ('خانم', 'خانم'), ('شرکت', 'شرکت'), ('دکتر', 'دکتر'), ('مهندس', 'مهندس'), (' مجتمع', ' مجتمع')], default='آقای', max_length=50, verbose_name='پیشوند')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره همراه')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('bio', models.CharField(blank=True, max_length=50, null=True, verbose_name='بیو')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='آدرس')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='full_name')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='authentication/images/profile/', verbose_name='تصویر')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], default='مرد', max_length=50, verbose_name='جنسیت')),
                ('type2', models.CharField(choices=[('حقیقی', 'حقیقی'), ('حقوقی', 'حقوقی')], default='حقیقی', max_length=50, verbose_name='نوع')),
                ('type', models.CharField(choices=[('مشتری', 'مشتری'), ('حقوقی', 'حقوقی'), ('پرسنل', 'پرسنل'), ('بدون کنترل', 'بدون کنترل')], default='بدون کنترل', max_length=50, verbose_name='ماهیت')),
                ('melli_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'اشخاص',
            },
            bases=(models.Model, utility.models.ImageHelper),
        ),
    ]
