# Generated by Django 5.2.1 on 2025-07-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='prefix',
            field=models.CharField(choices=[('آقای', 'آقای'), ('خانم', 'خانم'), ('شرکت', 'شرکت'), ('دکتر', 'دکتر'), ('مهندس', 'مهندس'), (' مجتمع', ' مجتمع'), ('فروشگاه', 'فروشگاه')], default='آقای', max_length=50, verbose_name='پیشوند'),
        ),
    ]
