# Generated by Django 5.1.6 on 2025-07-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان'),
        ),
    ]
