# Generated by Django 5.2.1 on 2025-07-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='melli_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
    ]
