# Generated by Django 5.2.1 on 2025-08-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_person_economic_no_person_postal_code_person_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='economic_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره اقتصادی'),
        ),
    ]
