# Generated by Django 5.2.1 on 2025-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_person_melli_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن'), ('دیگر', 'دیگر')], default='مرد', max_length=50, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
