# Generated by Django 5.2.1 on 2025-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_person_economic_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='prefix',
            field=models.CharField(choices=[('آقای', 'آقای'), ('خانم', 'خانم'), ('شرکت', 'شرکت'), ('دکتر', 'دکتر'), ('مهندس', 'مهندس'), (' مجتمع', ' مجتمع'), ('فروشگاه', 'فروشگاه'), ('دانشگاه', 'دانشگاه'), ('رستوران', 'رستوران'), ('آموزشگاه', 'آموزشگاه'), ('اداره', 'اداره')], default='آقای', max_length=50, verbose_name='پیشوند'),
        ),
    ]
