# Generated by Django 5.2.1 on 2025-08-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_person_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='محل تولد'),
        ),
    ]
