# Generated by Django 5.1.6 on 2025-07-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_person_title_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('مشتری', 'مشتری'), ('حقوقی', 'حقوقی'), ('حقیقی', 'حقیقی'), ('پرسنل', 'پرسنل'), ('بدون کنترل', 'بدون کنترل')], default='بدون کنترل', max_length=50, verbose_name='ماهیت'),
        ),
    ]
