# Generated by Django 5.2.1 on 2025-07-31 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_financialevent_creator'),
        ('archive', '0002_remove_folder_profiles_folder_persons_and_more'),
        ('attachments', '0007_remove_comment_profile_remove_download_profile_and_more'),
        ('authentication', '0004_remove_profile_user_remove_person_profile_and_more'),
        ('log', '0002_remove_log_profile_log_person'),
        ('messenger', '0002_remove_member_profile_member_person_and_more'),
        ('projectmanager', '0007_remove_ticket_profile_ticket_person'),
        ('warehouse', '0004_remove_materialport_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
