# Generated by Django 5.2.1 on 2025-08-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_person_birth_date_person_birth_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='موبایل'),
        ),
    ]
