# Generated by Django 5.2.1 on 2025-09-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_person_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='father_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نام پدر'),
        ),
    ]
