# Generated by Django 5.2.6 on 2025-09-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_person_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='melli_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='کد ملی'),
        ),
    ]
