# Generated by Django 5.2.1 on 2025-08-17 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0003_pageprint'),
        ('authentication', '0003_alter_person_economic_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_datetime', models.DateTimeField(verbose_name='enter date time')),
                ('exit_datetime', models.DateTimeField(verbose_name='exit date time')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attachments.location', verbose_name='location')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'Traffic',
                'verbose_name_plural': 'Traffics',
            },
        ),
    ]
