# Generated by Django 5.2.1 on 2025-08-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='enter_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='enter date time'),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='exit_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='exit date time'),
        ),
    ]
