# Generated by Django 5.2.1 on 2025-07-31 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
        ('authentication', '0003_alter_person_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='profiles',
        ),
        migrations.AddField(
            model_name='folder',
            name='persons',
            field=models.ManyToManyField(blank=True, to='authentication.person', verbose_name='persons'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders_owned', to='authentication.person', verbose_name='person'),
        ),
    ]
