# Generated by Django 5.2.6 on 2025-12-01 02:03

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0027_alter_invoiceline_unit_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('slogan', models.CharField(max_length=600, verbose_name='slogan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Cataloges',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
