# Generated by Django 5.2.1 on 2025-05-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='value',
        ),
        migrations.AddField(
            model_name='parameter',
            name='app_name',
            field=models.CharField(default='wererere', max_length=50, verbose_name='app_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='origin_value',
            field=models.CharField(blank=True, max_length=50000, null=True, verbose_name='مقدار پارامتر'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام پارامتر (تغییر ندهید)'),
        ),
    ]
