# Generated by Django 5.2.1 on 2025-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='utility/images/pictures/', verbose_name='image'),
        ),
    ]
