# Generated by Django 5.2.6 on 2025-09-13 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_person_father_name'),
        ('utility', '0002_alter_picture_image_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipBoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('text', models.CharField(max_length=100, verbose_name='text')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'ClipBoardItem',
                'verbose_name_plural': 'ClipBoardItems',
            },
        ),
    ]
