# Generated by Django 5.2.6 on 2025-09-20 22:40

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_person_father_name'),
        ('utility', '0003_clipboarditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000, verbose_name='url')),
                ('url', models.CharField(max_length=2000, verbose_name='url')),
                ('priority', models.IntegerField(default=100, verbose_name='priority')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'MyLink',
                'verbose_name_plural': 'MyLinks',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
