# Generated by Django 5.2.6 on 2025-09-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_alter_comment_parent'),
        ('authentication', '0007_person_father_name'),
        ('utility', '0003_clipboarditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attachments.link', verbose_name='link')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'MyLink',
                'verbose_name_plural': 'MyLinks',
            },
        ),
    ]
