# Generated by Django 5.2.4 on 2025-07-13 23:24

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.product')),
            ],
            options={
                'verbose_name': 'FoodItem',
                'verbose_name_plural': 'FoodItems',
            },
            bases=('accounting.product', utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoice')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
            },
            bases=('accounting.invoice',),
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('invoiceline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoiceline')),
            ],
            options={
                'verbose_name': 'MealItem',
                'verbose_name_plural': 'MealItems',
            },
            bases=('accounting.invoiceline', utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('items', models.ManyToManyField(to='chef.fooditem', verbose_name='food items')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
