# Generated by Django 5.2.1 on 2025-06-19 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='foods',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='قیمت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default='dfdfdf', max_length=50, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='datetime',
            field=models.DateTimeField(verbose_name='تاریخ'),
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('price', models.IntegerField(verbose_name='price')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef.fooditem', verbose_name='fooditem')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef.meal', verbose_name='meal')),
            ],
            options={
                'verbose_name': 'MealItem',
                'verbose_name_plural': 'MealItems',
            },
        ),
    ]
