# Generated by Django 5.2.1 on 2025-06-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='meal',
        ),
    ]
