# Generated by Django 5.2.1 on 2025-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeindex',
            name='image_header_origin',
            field=models.ImageField(blank=True, null=True, upload_to='resume/images/resume/header/', verbose_name='تصویر سربرگ'),
        ),
        migrations.AlterField(
            model_name='resumeindex',
            name='image_main_origin',
            field=models.ImageField(blank=True, null=True, upload_to='resume/images/resume/main/', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='resumetestimonial',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='resume/images/testimonial/', verbose_name='تصویر'),
        ),
    ]
