# Generated by Django 5.2.1 on 2025-09-04 14:32

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_alter_product_barcode'),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoice')),
            ],
            options={
                'verbose_name': 'نسخه',
                'verbose_name_plural': 'نسخه ها',
            },
            bases=('accounting.invoice',),
        ),
        migrations.CreateModel(
            name='PrescriptionLine',
            fields=[
                ('invoiceline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoiceline')),
            ],
            options={
                'verbose_name': 'PrescriptionLine',
                'verbose_name_plural': 'PrescriptionLines',
            },
            bases=('accounting.invoiceline',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.personaccount', verbose_name='person_account')),
            ],
            options={
                'verbose_name': 'دکتر',
                'verbose_name_plural': 'دکتر ها',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.personaccount', verbose_name='person_account')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
