# Generated by Django 5.1.6 on 2025-07-08 22:35

import django.core.files.storage
import django.db.models.deletion
import tinymce.models
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('authentication', '0005_alter_person_type'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='f:\\private_html\\phoenix11\\upload'), upload_to='attachments/downloads', verbose_name='فایل ضمیمه'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/images/Icon/', verbose_name='تصویر آیکون'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=50000, null=True, verbose_name='توضیحات')),
                ('priority', models.IntegerField(default=1000, verbose_name='priority')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='attachments/images/ImageBase/Thumbnail/', verbose_name='تصویر کوچک')),
                ('image_main_origin', models.ImageField(blank=True, null=True, upload_to='attachments/images/ImageBase/Main/', verbose_name='تصویر اصلی')),
                ('image_header_origin', models.ImageField(blank=True, null=True, upload_to='attachments/images/ImageBase/Header/', verbose_name='تصویر سربرگ')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='profile')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'تصاویر',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
