# Generated by Django 5.2.4 on 2025-07-13 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_area_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='page',
        ),
    ]
