# Generated by Django 5.2.1 on 2025-07-08 23:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_alter_download_file_alter_icon_image_origin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='d:\\private_html\\phoenix11\\upload'), upload_to='attachments/downloads', verbose_name='فایل ضمیمه'),
        ),
    ]
