# Generated by Django 5.2.1 on 2025-08-12 22:31

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_initial'),
        ('authentication', '0003_alter_person_economic_no'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('type', models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('رسمی', 'رسمی')], default='پیش نویس', max_length=50, verbose_name='type')),
                ('printed', models.BooleanField(default=False, verbose_name='printed')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'PagePrint',
                'verbose_name_plural': 'PagePrints',
            },
            bases=(models.Model, utility.models.DateTimeHelper),
        ),
    ]
