# Generated by Django 5.1.6 on 2025-07-15 21:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_alter_download_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='f:\\private_html\\phoenix11\\upload'), upload_to='attachments/downloads', verbose_name='فایل ضمیمه'),
        ),
    ]
