# Generated by Django 5.2.6 on 2025-09-20 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_alter_comment_parent'),
        ('core', '0006_alter_page_description_alter_page_meta_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page'),
        ),
    ]
