# Generated by Django 5.1.6 on 2025-07-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(default='eeeeeeeeeeeee', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
    ]
