# Generated by Django 5.2.1 on 2025-07-31 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0006_alter_download_file'),
        ('authentication', '0003_alter_person_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='download',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='download',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='like',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='link',
            name='profile',
        ),
        migrations.AddField(
            model_name='comment',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='download',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person'),
        ),
        migrations.AddField(
            model_name='download',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='person_downloads', to='authentication.person', verbose_name='persons'),
        ),
        migrations.AddField(
            model_name='like',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='image',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='location',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maplocation_set', to='authentication.person', verbose_name='person'),
        ),
    ]
