# Generated by Django 5.2.1 on 2025-05-22 13:07

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('muted', 'muted'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='color')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('type', models.CharField(choices=[('گروه', 'گروه'), ('کل', 'کل'), ('معین 1', 'معین 1'), ('معین 2', 'معین 2'), ('تفصیلی 1', 'تفصیلی 1'), ('تفصیلی 2', 'تفصیلی 2'), ('تفصیلی 3', 'تفصیلی 3'), ('تفصیلی 4', 'تفصیلی 4'), ('تفصیلی 5', 'تفصیلی 5'), ('تفصیلی 6', 'تفصیلی 6')], max_length=50, verbose_name='نوع')),
                ('nature', models.CharField(choices=[('بستانکار', 'بستانکار'), ('فقط بستانکار', 'فقط بستانکار'), ('بدهکار', 'بدهکار'), ('فقط بدهکار', 'فقط بدهکار'), ('بدون کنترل', 'بدون کنترل')], default='بدون کنترل', max_length=50, verbose_name='ماهیت')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('logo_origin', models.ImageField(blank=True, null=True, upload_to='images/account', verbose_name='logo')),
                ('priority', models.IntegerField(default=100)),
                ('bedehkar', models.IntegerField(default=0, verbose_name='bedehkar')),
                ('bestankar', models.IntegerField(default=0, verbose_name='bestankar')),
                ('balance', models.IntegerField(default=0, verbose_name='balance')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
