# Generated by Django 5.2.1 on 2025-05-27 02:33

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('muted', 'muted'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='color')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('type', models.CharField(choices=[('گروه', 'گروه'), ('کل', 'کل'), ('معین 1', 'معین 1'), ('معین 2', 'معین 2'), ('تفصیلی 1', 'تفصیلی 1'), ('تفصیلی 2', 'تفصیلی 2'), ('تفصیلی 3', 'تفصیلی 3'), ('تفصیلی 4', 'تفصیلی 4'), ('تفصیلی 5', 'تفصیلی 5'), ('تفصیلی 6', 'تفصیلی 6')], max_length=50, verbose_name='نوع')),
                ('nature', models.CharField(choices=[('بستانکار', 'بستانکار'), ('فقط بستانکار', 'فقط بستانکار'), ('بدهکار', 'بدهکار'), ('فقط بدهکار', 'فقط بدهکار'), ('بدون کنترل', 'بدون کنترل')], default='بدون کنترل', max_length=50, verbose_name='ماهیت')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('logo_origin', models.ImageField(blank=True, null=True, upload_to='images/account', verbose_name='logo')),
                ('level', models.IntegerField(verbose_name='level')),
                ('priority', models.IntegerField(default=100, verbose_name='priority')),
                ('bedehkar', models.IntegerField(default=0, verbose_name='bedehkar')),
                ('bestankar', models.IntegerField(default=0, verbose_name='bestankar')),
                ('balance', models.IntegerField(default=0, verbose_name='balance')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'حساب ها',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='FinancialEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('tax_percentage', models.IntegerField(default=-1, verbose_name='درصد مالیات')),
                ('amount', models.IntegerField(default=0, verbose_name='مبلغ')),
                ('discount_percentage', models.IntegerField(default=0, verbose_name='درصد تخفیف')),
                ('payment_method', models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('همراه بانک', 'همراه بانک'), ('فروش کالا', 'فروش کالا'), ('فروش خدمات', 'فروش خدمات'), ('نقدی', 'نقدی'), ('چک', 'چک'), ('کارتخوان', 'کارتخوان'), ('فیش بانکی', 'فیش بانکی'), ('کارت به کارت', 'کارت به کارت')], default='پیش نویس', max_length=50, verbose_name='نوع پرداخت')),
                ('bedehkar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bedehkar_events', to='accounting.account', verbose_name='دریافت کننده')),
                ('bestankar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bestankar_events', to='accounting.account', verbose_name='پرداخت کننده')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile', verbose_name='ثبت شده توسط')),
            ],
            options={
                'verbose_name': 'رویداد مالی',
                'verbose_name_plural': 'رویداد های مالی',
            },
            bases=('core.event', utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
            ],
            options={
                'verbose_name': 'InvoiceLineItem',
                'verbose_name_plural': 'InvoiceLineItems',
            },
            bases=('core.page', utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='PersonAccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
            ],
            options={
                'verbose_name': 'PersonAccountCategory',
                'verbose_name_plural': 'دسته بندی حساب های اشخاص',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('financialevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.financialevent')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'فاکتور ها',
            },
            bases=('accounting.financialevent',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('invoicelineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoicelineitem')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='barcode')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'کالا ها',
            },
            bases=('accounting.invoicelineitem',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('invoicelineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoicelineitem')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'خدمات',
            },
            bases=('accounting.invoicelineitem',),
        ),
        migrations.CreateModel(
            name='InvoiceLineItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('کیلوگرم', 'کیلوگرم'), ('متر', 'متر'), ('شاخه', 'شاخه'), ('دستگاه', 'دستگاه'), ('گرم', 'گرم'), ('ورق', 'ورق'), ('تن', 'تن'), ('خط', 'خط'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('روز', 'روز'), ('تخته', 'تخته'), ('لینک', 'لینک'), ('سرویس', 'سرویس'), ('مورد', 'مورد'), ('نفر', 'نفر'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست'), ('کارتن', 'کارتن'), ('ساعت', 'ساعت'), ('دقیقه', 'دقیقه'), ('جعبه', 'جعبه'), ('سبد', 'سبد'), ('راس', 'راس')], max_length=50, verbose_name='unit_name')),
                ('coef', models.FloatField(default=1, verbose_name='coef')),
                ('unit_price', models.IntegerField(default=1, verbose_name='unit_price')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ')),
                ('invoice_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.invoicelineitem', verbose_name='invoicelineitem')),
            ],
            options={
                'verbose_name': 'InvoiceLineItemUnit',
                'verbose_name_plural': 'InvoiceLineItemUnits',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'اشخاص',
            },
        ),
        migrations.CreateModel(
            name='PersonAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.personaccountcategory', verbose_name='person account category')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'PersonAccount',
                'verbose_name_plural': 'حساب های اشخاص',
            },
            bases=('accounting.account',),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('کیلوگرم', 'کیلوگرم'), ('متر', 'متر'), ('شاخه', 'شاخه'), ('دستگاه', 'دستگاه'), ('گرم', 'گرم'), ('ورق', 'ورق'), ('تن', 'تن'), ('خط', 'خط'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('روز', 'روز'), ('تخته', 'تخته'), ('لینک', 'لینک'), ('سرویس', 'سرویس'), ('مورد', 'مورد'), ('نفر', 'نفر'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست'), ('کارتن', 'کارتن'), ('ساعت', 'ساعت'), ('دقیقه', 'دقیقه'), ('جعبه', 'جعبه'), ('سبد', 'سبد'), ('راس', 'راس')], max_length=50, verbose_name='unit_name')),
                ('unit_price', models.IntegerField(verbose_name='unit_price')),
                ('discount_percentage', models.IntegerField(verbose_name='discount_percentage')),
                ('tax_amount', models.IntegerField(verbose_name='tax_amount')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='description')),
                ('invoice_line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.invoicelineitem', verbose_name='invoice_line_item')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.invoice', verbose_name='invoice')),
            ],
            options={
                'verbose_name': 'InvoiceLine',
                'verbose_name_plural': 'سطر های فاکتور ها',
            },
        ),
    ]
