# Generated by Django 5.2.1 on 2025-05-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='row',
            field=models.IntegerField(default=1, verbose_name='row      '),
            preserve_default=False,
        ),
    ]
