# Generated by Django 5.2.1 on 2025-05-26 22:01

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('authentication', '0002_profile_user'),
        ('core', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('color_origin', models.CharField(blank=True, choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('muted', 'muted'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], max_length=50, null=True, verbose_name='color')),
            ],
            options={
                'verbose_name': 'EventCategory',
                'verbose_name_plural': 'EventCategories',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.AddField(
            model_name='account',
            name='level',
            field=models.IntegerField(default=-1, verbose_name='level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='priority'),
        ),
        migrations.CreateModel(
            name='FinancialEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('tax_percent', models.IntegerField(default=-1, verbose_name='درصد مالیات')),
                ('amount', models.IntegerField(default=0, verbose_name='مبلغ')),
                ('discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('payment_method', models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('همراه بانک', 'همراه بانک'), ('فروش کالا', 'فروش کالا'), ('فروش خدمات', 'فروش خدمات'), ('نقدی', 'نقدی'), ('چک', 'چک'), ('کارتخوان', 'کارتخوان'), ('فیش بانکی', 'فیش بانکی'), ('کارت به کارت', 'کارت به کارت')], default='پیش نویس', max_length=50, verbose_name='نوع پرداخت')),
                ('bedehkar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bedehkar_events', to='accounting.account', verbose_name='دریافت کننده')),
                ('bestankar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bestankar_events', to='accounting.account', verbose_name='پرداخت کننده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.eventcategory', verbose_name='دسته بندی')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile', verbose_name='ثبت شده توسط')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
            bases=('core.event', utility.models.DateTimeHelper),
        ),
    ]
