# Generated by Django 5.2.1 on 2025-07-06 21:10

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('priority', models.IntegerField(default=100, verbose_name='priority')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='images/ImageBase/Thumbnail/', verbose_name='تصویر کوچک')),
                ('header_origin', models.ImageField(blank=True, null=True, upload_to='images/ImageBase/Header/', verbose_name='تصویر سربرگ')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.category', verbose_name='parent')),
                ('products', models.ManyToManyField(blank=True, to='accounting.product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.ImageHelper),
        ),
    ]
