# Generated by Django 5.2.1 on 2025-08-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='quantity',
            field=models.FloatField(verbose_name='quantity'),
        ),
    ]
