# Generated by Django 5.2.1 on 2025-05-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicelineitemunit',
            old_name='unit_barcodename',
            new_name='unit_name',
        ),
    ]
