# Generated by Django 5.2.1 on 2025-06-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaccount',
            options={'verbose_name': 'PersonAccount', 'verbose_name_plural': 'حساب های اشخاص'},
        ),
    ]
