# Generated by Django 5.2.1 on 2025-07-08 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_category'),
        ('authentication', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaccount',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.person', verbose_name='person'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
