# Generated by Django 5.2.1 on 2025-06-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_personaccount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitemunit',
            name='default',
            field=models.BooleanField(default=False, verbose_name='default'),
        ),
    ]
