# Generated by Django 5.1.6 on 2025-07-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_asset_delete_personaccountcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcategory',
            name='title',
            field=models.CharField(choices=[('پیش فرض', 'پیش فرض'), ('مشتری', 'مشتری'), ('فروشنده', 'فروشنده'), ('پرسنل', 'پرسنل'), ('سهامدار', 'سهامدار'), ('پیمانکار', 'پیمانکار'), ('کارفرما', 'کارفرما'), ('هزینه', 'هزینه')], default='پیش فرض', max_length=50, verbose_name='title'),
        ),
    ]
