# Generated by Django 5.2.1 on 2025-08-03 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_invoiceline_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.personaccount', verbose_name='owner'),
        ),
    ]
