# Generated by Django 5.2.4 on 2025-08-03 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_asset_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_ptr',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='person',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='personaccount_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.personaccount'),
            preserve_default=False,
        ),
    ]
