# Generated by Django 5.1.6 on 2025-07-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_personcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='code'),
        ),
    ]
