# Generated by Django 5.2.1 on 2025-07-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_invoiceline_unit_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'دارایی', 'verbose_name_plural': 'دارایی ها'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'بانک', 'verbose_name_plural': 'بانک ها'},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'حساب بانکی', 'verbose_name_plural': 'حساب های بانکی'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برند ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='financialdocument',
            options={'verbose_name': 'سند مالی', 'verbose_name_plural': 'سند های مالی'},
        ),
        migrations.AlterModelOptions(
            name='financialdocumentline',
            options={'verbose_name': 'سطر سند حسابداری', 'verbose_name_plural': 'سطر های سند حسابداری'},
        ),
        migrations.AlterModelOptions(
            name='financialyear',
            options={'verbose_name': 'سال مالی', 'verbose_name_plural': 'سال های مالی'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'فاکتور', 'verbose_name_plural': 'فاکتور ها'},
        ),
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'verbose_name': 'InvoiceLineItem', 'verbose_name_plural': 'موارد قابل فروش'},
        ),
        migrations.AlterModelOptions(
            name='invoicelineitemunit',
            options={'verbose_name': 'InvoiceLineItemUnit', 'verbose_name_plural': 'واحد های قابل فروش'},
        ),
        migrations.AlterModelOptions(
            name='personcategory',
            options={'verbose_name': 'دسته بندی اشخاص', 'verbose_name_plural': 'دسته بندی های اشخاص'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'کالا', 'verbose_name_plural': 'کالا ها'},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'verbose_name': 'ProductSpecification', 'verbose_name_plural': 'ویژگی های محصولات'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_fee',
            field=models.IntegerField(default=0, verbose_name='هزینه حمل'),
        ),
    ]
