# Generated by Django 5.2.1 on 2025-06-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_invoicelineitemunit_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='discount_percentage',
            field=models.IntegerField(default=0, verbose_name='discount_percentage'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='row',
            field=models.IntegerField(default=0, verbose_name='row'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='tax_amount',
            field=models.IntegerField(default=0, verbose_name='tax_amount'),
        ),
    ]
