# Generated by Django 5.2.1 on 2025-08-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_asset_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='bank',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='bank',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tel'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='account_no'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='card_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='card_no'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='shaba_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='shaba_no'),
        ),
    ]
