# Generated by Django 5.2.1 on 2025-08-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_bank_address_bank_branch_bank_tel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_origin',
            field=models.ImageField(blank=True, null=True, upload_to='images/account', verbose_name='logo'),
        ),
    ]
