# Generated by Django 5.2.1 on 2025-07-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_asset_options_alter_bank_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_fee',
        ),
        migrations.AddField(
            model_name='financialevent',
            name='shipping_fee',
            field=models.IntegerField(default=0, verbose_name='هزینه حمل'),
        ),
        migrations.AlterField(
            model_name='financialevent',
            name='tax_percentage',
            field=models.IntegerField(default=0, verbose_name='درصد مالیات'),
        ),
    ]
