# Generated by Django 5.2.4 on 2025-08-03 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_bankaccount_account_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='account_no',
            new_name='account_nooo',
        ),
    ]
