# Generated by Django 5.2.1 on 2025-08-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_brand_logo_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='logo_origin',
        ),
    ]
