# Generated by Django 5.2.1 on 2025-07-04 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_invoiceline_unit_name_and_more'),
        ('core', '0002_remove_like_page_remove_like_profile_delete_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDocument',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('bestankar', models.IntegerField(default=0, verbose_name='bestankar')),
                ('bedehkar', models.IntegerField(default=0, verbose_name='bedehkar')),
                ('event_datetime', models.DateTimeField(verbose_name='event_datetime')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
                ('financial_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.financialevent', verbose_name='financial_event')),
            ],
            options={
                'verbose_name': 'FinancialDocument',
                'verbose_name_plural': 'FinancialDocuments',
            },
            bases=('core.page',),
        ),
    ]
