# Generated by Django 5.2.1 on 2025-08-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_account_logo_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialevent',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='financialevent',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
    ]
