# Generated by Django 5.2.1 on 2025-07-31 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_invoiceline_unit_name_and_more'),
        ('authentication', '0003_alter_person_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialevent',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.person', verbose_name='ثبت شده توسط'),
        ),
    ]
