# Generated by Django 5.2.1 on 2025-08-27 15:45

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_invoiceline_unit_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('financialevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.financialevent')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='accounting/images/cheque/', verbose_name='تصویر')),
            ],
            bases=('accounting.financialevent', utility.models.ImageHelper),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo_origin',
            field=models.ImageField(blank=True, null=True, upload_to='accounting/images/brand', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='header_origin',
            field=models.ImageField(blank=True, null=True, upload_to='accounting/images/category/header/', verbose_name='تصویر سربرگ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail_origin',
            field=models.ImageField(blank=True, null=True, upload_to='accounting/images/category/thumbnail/', verbose_name='تصویر کوچک'),
        ),
    ]
