# Generated by Django 5.2.1 on 2025-08-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_alter_invoiceline_unit_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='tax_amount',
            field=models.IntegerField(default=0, verbose_name='مالیات'),
        ),
    ]
