# Generated by Django 5.2.1 on 2025-08-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_financialevent_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='sum_total',
            field=models.IntegerField(default=0, verbose_name='مبلغ نهایی'),
        ),
    ]
