# Generated by Django 5.2.1 on 2025-08-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_financialevent_sum_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='barcode'),
        ),
    ]
