# Generated by Django 5.2.1 on 2025-09-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_invoiceline_unit_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialevent',
            name='creator',
        ),
    ]
