# Generated by Django 5.2.1 on 2025-09-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_remove_financialevent_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='status',
            field=models.CharField(blank=True, choices=[('نو', 'نو'), ('کارکرده', 'کارکرده'), ('کارکرده در حد نو', 'کارکرده در حد نو'), ('نو بدون جعبه', 'نو بدون جعبه'), ('تعمیر شده', 'تعمیر شده')], max_length=5000, null=True, verbose_name='status'),
        ),
    ]
