# Generated by Django 5.2.6 on 2025-09-13 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_invoiceline_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdocumentline',
            name='financial_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.financialdocument', verbose_name='accountingdocument'),
        ),
    ]
