# Generated by Django 5.2.6 on 2025-09-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_alter_financialdocumentline_financial_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocumentline',
            name='status',
            field=models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('رد شده', 'رد شده'), ('تایید شده', 'تایید شده')], default='پیش نویس', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='status',
            field=models.CharField(blank=True, choices=[('نو', 'نو'), ('کارکرده', 'کارکرده'), ('کارکرده در حد نو', 'کارکرده در حد نو'), ('نو بدون جعبه', 'نو بدون جعبه'), ('تعمیر شده', 'تعمیر شده'), ('خراب', 'خراب'), ('داغون', 'داغون'), ('قلابی', 'قلابی'), ('اصلی', 'اصلی')], max_length=5000, null=True, verbose_name='status'),
        ),
    ]
