# Generated by Django 5.2.6 on 2025-09-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_invoiceline_invoice'),
        ('authentication', '0008_alter_person_melli_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person'),
        ),
    ]
