# Generated by Django 5.2.6 on 2025-10-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_invoiceline_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.IntegerField(default=0, verbose_name='invoice_no'),
        ),
    ]
