# Generated by Django 5.2.6 on 2025-10-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_invoice_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rop',
            field=models.IntegerField(default=0, verbose_name='نثطه سفارش مجدد'),
        ),
    ]
