# Generated by Django 5.2.6 on 2025-10-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_product_rop'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='valid'),
        ),
    ]
