# Generated by Django 5.2.6 on 2025-11-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_financialevent_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialevent',
            name='sum_total',
        ),
    ]
