# Generated by Django 5.2.4 on 2025-07-12 23:20

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('attachments', '0002_area_location'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEvent',
            fields=[
                ('financialevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.financialevent')),
                ('kilometer', models.IntegerField(blank=True, null=True, verbose_name='کارکرد')),
            ],
            options={
                'verbose_name': 'VehicleEvent',
                'verbose_name_plural': 'VehicleEvents',
            },
            bases=('accounting.financialevent',),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('financialevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.financialevent')),
                ('distance', models.IntegerField(verbose_name='distance')),
                ('duration', models.IntegerField(verbose_name='duration')),
                ('date_started', models.DateTimeField(blank=True, null=True, verbose_name='شروع سرویس')),
                ('date_ended', models.DateTimeField(blank=True, null=True, verbose_name='پایان سرویس')),
                ('delay', models.IntegerField(default=0, verbose_name='تاخیر')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
            bases=('accounting.financialevent',),
        ),
        migrations.CreateModel(
            name='TripCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('muted', 'muted'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'TripCategory',
                'verbose_name_plural': 'TripCategorys',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.asset')),
                ('vehicle_type', models.CharField(choices=[('موتورسیکلت', 'موتورسیکلت'), ('وانت', 'وانت'), ('سواری', 'سواری'), ('اتوبوس', 'اتوبوس'), ('تاکسی', 'تاکسی'), ('گریدر', 'گریدر'), ('لودر', 'لودر'), ('تریلی', 'تریلی'), ('کانتینر', 'کانتینر'), ('سپراتور', 'سپراتور'), ('خاور', 'خاور')], default='سواری', max_length=50, verbose_name='نوع وسیله ')),
                ('brand_name', models.CharField(choices=[('تویوتا', 'تویوتا'), ('پژو', 'پژو'), ('بنز', 'بنز'), ('ایسوزو', 'ایسوزو'), ('اسکانیا', 'اسکانیا'), ('مزدا', 'مزدا'), ('ولوو', 'ولوو'), ('پیشتاز', 'پیشتاز'), ('کاترپیلار', 'کاترپیلار'), ('هیوندای', 'هیوندای'), ('هووو', 'هووو'), ('دانگ فنگ', 'دانگ فنگ'), ('سایپا', 'سایپا'), ('داف', 'داف'), ('ایران خودرو', 'ایران خودرو'), ('XCMG', 'XCMG')], default='ایران خودرو', max_length=50, verbose_name='برند')),
                ('model_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدل')),
                ('plaque', models.CharField(blank=True, max_length=50, null=True, verbose_name='پلاک')),
                ('driver', models.CharField(blank=True, max_length=50, null=True, verbose_name='راننده')),
                ('vehicle_color', models.CharField(choices=[('سفید', 'سفید'), ('سیاه', 'سیاه'), ('نوک مدادی', 'نوک مدادی'), ('دلفینی', 'دلفینی'), ('بژ', 'بژ'), ('قرمز', 'قرمز')], default='سفید', max_length=50, verbose_name='رنگ')),
                ('kilometer', models.IntegerField(default=0, verbose_name='کیلومتر')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
            bases=('accounting.asset',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Client',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('muted', 'muted'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='color')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.driver', verbose_name='driver')),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateHelper),
        ),
        migrations.CreateModel(
            name='FuelSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liter', models.IntegerField(verbose_name='liter')),
                ('unit_buy_price', models.IntegerField(verbose_name='خرید هر لیتر')),
                ('unit_sell_price', models.IntegerField(verbose_name='فروش هر لیتر')),
                ('date', models.DateField(verbose_name='date')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.cycle', verbose_name='cycle')),
                ('variz_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccount', verbose_name='bank_account')),
            ],
            options={
                'verbose_name': 'FuelSell',
                'verbose_name_plural': 'FuelSells',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateHelper),
        ),
        migrations.CreateModel(
            name='Hazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('صبحانه', 'صبحانه'), ('نهار', 'نهار'), ('شام', 'شام'), ('پارکینگ', 'پارکینگ'), ('عوارض', 'عوارض'), ('انعام', 'انعام'), ('حمام', 'حمام'), ('شارژ سیمکارت', 'شارژ سیمکارت'), ('شارژ اینترنت', 'شارژ اینترنت'), ('کل صورت خرجکرد', 'کل صورت خرجکرد')], max_length=50, verbose_name='name')),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.cycle', verbose_name='cycle')),
                ('variz_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazinefromset', to='accounting.bankaccount', verbose_name='bank_account')),
            ],
            options={
                'verbose_name': 'Hazine',
                'verbose_name_plural': 'Hazines',
            },
            bases=(models.Model, utility.models.DateHelper, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('weight', models.IntegerField(default=0, verbose_name='وزن')),
                ('is_fragile', models.BooleanField(default=False, verbose_name='شکستنی است؟')),
                ('weight_unit', models.CharField(choices=[('کیلوگرم', 'کیلوگرم'), ('گرم', 'گرم'), ('تن', 'تن')], default='کیلوگرم', max_length=50, verbose_name='واحد وزن')),
                ('length', models.IntegerField(default=0, verbose_name='طول')),
                ('width', models.IntegerField(default=0, verbose_name='عرض')),
                ('height', models.IntegerField(default=0, verbose_name='ارتفاع')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Luggage',
                'verbose_name_plural': 'Luggages',
            },
            bases=('core.page', utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('vehicleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport.vehicleevent')),
                ('maintenance_type', models.CharField(choices=[('شستشو', 'شستشو'), ('سوخت', 'سوخت'), ('تعمیر موتور', 'تعمیر موتور'), ('بیمه', 'بیمه'), ('برق خودرو', 'برق خودرو'), ('لاستیک', 'لاستیک'), ('بدنه', 'بدنه'), ('جلوبندی', 'جلوبندی'), ('تعویض روغن', 'تعویض روغن')], max_length=100, verbose_name='سرویس')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
            },
            bases=('transport.vehicleevent',),
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='ServiceMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'ServiceMan',
                'verbose_name_plural': 'ServiceMans',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('trip_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport.trip')),
                ('load', models.CharField(blank=True, max_length=200, null=True, verbose_name='بار')),
                ('ghabz_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره قبض')),
                ('barnameh_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره بارنامه')),
                ('date_sent', models.DateTimeField(verbose_name='تاریخ ارسال')),
                ('date_delivered', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
            },
            bases=('transport.trip', utility.models.LinkHelper),
        ),
        migrations.AddField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(blank=True, to='transport.passenger', verbose_name='مسافر ها'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.tripcategory', verbose_name='نوع سفر'),
        ),
        migrations.CreateModel(
            name='TripPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0, verbose_name='هزینه')),
                ('distance', models.IntegerField(default=0, verbose_name='فاصله')),
                ('duration', models.IntegerField(default=0, verbose_name='مدت زمان تقریبی')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attachments.area', verbose_name='area')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_destination_set', to='attachments.location', verbose_name='مقصد')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_source_set', to='attachments.location', verbose_name='مبدا')),
            ],
            options={
                'verbose_name': 'TripPath',
                'verbose_name_plural': 'TripPaths',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_paths',
            field=models.ManyToManyField(blank=True, to='transport.trippath', verbose_name='مسیر های سرویس'),
        ),
        migrations.CreateModel(
            name='Barname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0, verbose_name='مدت زمان تقریبی')),
                ('distance', models.IntegerField(default=0, verbose_name='فاصله')),
                ('load', models.CharField(max_length=50, verbose_name='بار')),
                ('cost', models.IntegerField(default=0, verbose_name='کرایه بار')),
                ('anam', models.IntegerField(verbose_name='انعام')),
                ('commision', models.IntegerField(default=0, verbose_name='کمیسیون')),
                ('driver_wage', models.IntegerField(default=0, verbose_name='سهم راننده')),
                ('start_date', models.DateField(verbose_name='شروع حرکت')),
                ('end_date', models.DateField(verbose_name='پایان حرکت')),
                ('variz_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccount', verbose_name='واریز به')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.cycle', verbose_name='cycle')),
                ('trip_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.trippath', verbose_name='مسیر')),
            ],
            options={
                'verbose_name': 'Barname',
                'verbose_name_plural': 'Barnames',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateHelper),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport.vehicle')),
            ],
            options={
                'verbose_name': 'Truck',
                'verbose_name_plural': 'Trucks',
            },
            bases=('transport.vehicle', utility.models.LinkHelper),
        ),
        migrations.AddField(
            model_name='vehicleevent',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle', verbose_name='ماشین'),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle', verbose_name='vehicle'),
        ),
        migrations.CreateModel(
            name='Variz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.cycle', verbose_name='cycle')),
                ('variz_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varizfromset', to='accounting.bankaccount', verbose_name='bank_account')),
                ('variz_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variztoset', to='accounting.bankaccount', verbose_name='bank_account')),
            ],
            options={
                'verbose_name': 'Variz',
                'verbose_name_plural': 'Varizs',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateHelper),
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('financialevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.financialevent')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'WorkShift',
                'verbose_name_plural': 'WorkShifts',
            },
            bases=('accounting.financialevent',),
        ),
        migrations.CreateModel(
            name='VehicleWorkEvent',
            fields=[
                ('vehicleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport.vehicleevent')),
                ('event_type', models.CharField(choices=[('لاستیک پنچر', 'لاستیک پنچر'), ('شیشه شکسته', 'شیشه شکسته'), ('خسارت مالی', 'خسارت مالی'), ('خسارت جانی', 'خسارت جانی')], max_length=50, verbose_name='event_type')),
                ('work_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.workshift', verbose_name='شیفت کاری')),
            ],
            options={
                'verbose_name': 'VehicleWorkEvent',
                'verbose_name_plural': 'VehicleWorkEvents',
            },
            bases=('transport.vehicleevent',),
        ),
        migrations.AddField(
            model_name='cycle',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.truck', verbose_name='truck'),
        ),
    ]
