# Generated by Django 5.2.6 on 2025-09-16 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_alter_financialdocumentline_financial_document'),
        ('core', '0006_alter_page_description_alter_page_meta_data_and_more'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('kilometer', models.IntegerField(default=0, verbose_name='کیلومتر')),
                ('maintenance_type', models.CharField(choices=[('شستشو', 'شستشو'), ('سوخت', 'سوخت'), ('تعمیر موتور', 'تعمیر موتور'), ('بیمه', 'بیمه'), ('برق خودرو', 'برق خودرو'), ('لاستیک', 'لاستیک'), ('بدنه', 'بدنه'), ('جلوبندی', 'جلوبندی'), ('تعویض روغن', 'تعویض روغن')], max_length=100, verbose_name='سرویس')),
                ('invoices', models.ManyToManyField(blank=True, to='accounting.invoice', verbose_name='invoice')),
                ('service_man', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.serviceman', verbose_name='service man')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
            },
            bases=('core.event',),
        ),
    ]
