# Generated by Django 5.2.1 on 2025-08-01 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_financialevent_creator'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceman',
            name='account',
        ),
        migrations.RemoveField(
            model_name='serviceman',
            name='title',
        ),
        migrations.AddField(
            model_name='serviceman',
            name='person_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.personaccount', verbose_name='person_account'),
            preserve_default=False,
        ),
    ]
