# Generated by Django 5.2.6 on 2026-05-09 02:24

import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'Desk',
                'verbose_name_plural': 'Desks',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
