# Generated by Django 5.2.6 on 2026-04-29 15:01

import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('table_no', models.IntegerField(default=0, verbose_name='شماره میز')),
            ],
            options={
                'verbose_name': 'MealItem',
                'verbose_name_plural': 'MealItems',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
