# Generated by Django 5.2.1 on 2025-08-23 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_person_economic_no'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('person_to_meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointmentes',
            },
            bases=('core.event',),
        ),
    ]
