# Generated by Django 5.2.1 on 2025-09-06 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_person_father_name'),
        ('core', '0006_alter_page_description_alter_page_meta_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.task')),
                ('persons_to_meet', models.ManyToManyField(to='authentication.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointmentes',
            },
            bases=('scheduler.task',),
        ),
    ]
